#!/usr/bin/env node
/**
 * Phase One Visuals — Save Context
 * 
 * Run this at the end of every session to persist everything:
 *   node automation/save-context.js
 * 
 * What it does:
 *   1. Reads current git status to capture what was changed
 *   2. Saves a session log to obsidian-vault/workflow-logs/
 *   3. Creates OpenBrain-ready findings for any new decisions
 *   4. Commits and pushes to GitHub so next chat anywhere can pull context
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'fs';
import { join } from 'path';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const CWD = process.cwd();
const LOGS_DIR = join(CWD, 'obsidian-vault', 'workflow-logs');
const FINDINGS_DIR = join(CWD, 'obsidian-vault', 'openbrain-findings');

// ─── Ensure directories ───
[LOGS_DIR, FINDINGS_DIR].forEach(dir => {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
});

// ─── Helpers ───
function getTimestamp() {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  const h = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');
  return `${y}-${m}-${d}-${h}${min}`;
}

function getGitStatus() {
  try {
    const status = execSync('git status --short', { cwd: CWD, encoding: 'utf8', stdio: 'pipe' });
    return status || '(no changes)';
  } catch {
    return '(could not get git status)';
  }
}

function getModifiedFiles() {
  try {
    const status = execSync('git diff --name-only', { cwd: CWD, encoding: 'utf8', stdio: 'pipe' });
    const staged = execSync('git diff --cached --name-only', { cwd: CWD, encoding: 'utf8', stdio: 'pipe' });
    const untracked = execSync('git ls-files --others --exclude-standard', { cwd: CWD, encoding: 'utf8', stdio: 'pipe' });
    return [...new Set([
      ...status.trim().split('\n'),
      ...staged.trim().split('\n'),
      ...untracked.trim().split('\n')
    ].filter(Boolean))];
  } catch {
    return [];
  }
}

function getLastSessionLog() {
  try {
    const files = readdirSync(LOGS_DIR)
      .filter(f => f.startsWith('session-') && f.endsWith('.md'))
      .map(f => ({
        name: f,
        path: join(LOGS_DIR, f),
        mtime: statSync(join(LOGS_DIR, f)).mtime
      }))
      .sort((a, b) => b.mtime - a.mtime);

    if (files.length > 0) {
      return {
        filename: files[0].name,
        modified: files[0].mtime,
        preview: readFileSync(files[0].path, 'utf8').split('\n').slice(0, 8).join('\n')
      };
    }
  } catch {}
  return null;
}

function gitCommitAndPush(message) {
  try {
    const status = execSync('git status --porcelain', { cwd: CWD, encoding: 'utf8', stdio: 'pipe' });
    if (!status.trim()) {
      console.log('  ✓ No uncommitted changes to push');
      return;
    }
    execSync('git add obsidian-vault/ automation/ .clinerules .graphifyignore', { cwd: CWD, stdio: 'pipe' });
    execSync(`git commit -m "${message}"`, { cwd: CWD, stdio: 'pipe' });
    execSync('git push origin master', { cwd: CWD, stdio: 'pipe' });
    console.log('  ✓ Pushed to GitHub — context available from any chat');
  } catch (err) {
    console.log(`  ⚠️  Git push skipped: ${err.message.split('\n')[0]}`);
  }
}

// ─── Main ───
async function main() {
  console.log('');
  console.log('╔═══════════════════════════════════════════════╗');
  console.log('║   Phase One Visuals — Save Context Pipeline  ║');
  console.log('╚═══════════════════════════════════════════════╝');
  console.log('');

  // 1. Gather context
  const timestamp = getTimestamp();
  const modifiedFiles = getModifiedFiles();
  const gitStatus = getGitStatus();
  const lastSession = getLastSessionLog();

  console.log(`  📁 Files modified this session: ${modifiedFiles.length}`);
  modifiedFiles.forEach(f => console.log(`     • ${f}`));
  console.log('');

  // 2. Prompt for session notes (will be passed via prompt or use defaults)
  console.log('  📝 Creating session log...');
  let sessionNotes = process.argv.slice(2).join(' ') || '(Session notes not provided)';

  // 3. Write session log
  const logContent = [
    `# Session Log — ${timestamp}`,
    '',
    '## Summary',
    sessionNotes,
    '',
    '## Files Modified',
    ...(modifiedFiles.length > 0 ? modifiedFiles.map(f => `- \`${f}\``) : ['- (none)']),
    '',
    '## Git Status',
    '```',
    gitStatus,
    '```',
    '',
    '## Previous Context',
    lastSession ? `Last session: ${lastSession.filename} (${lastSession.modified})` : '(first session)',
    '',
    '---',
    'Auto-generated by save-context.js'
  ].join('\n');

  const logFile = join(LOGS_DIR, `session-${timestamp}.md`);
  writeFileSync(logFile, logContent, 'utf8');
  console.log(`  ✓ Session log: ${logFile}`);

  // 4. Prepare OpenBrain findings
  if (modifiedFiles.length > 0) {
    const findingFile = join(FINDINGS_DIR, `${timestamp}-session-summary.md`);
    const findingContent = [
      '---',
      `title: "Session Summary — ${timestamp}"`,
      'type: session',
      `session: "${timestamp}"`,
      `created: "${new Date().toISOString()}"`,
      `tags: ["session", "${timestamp.split('-')[0]}"]`,
      '---',
      '',
      `# Session Summary — ${timestamp}`,
      '',
      sessionNotes,
      '',
      '## Files Changed',
      ...modifiedFiles.map(f => `- \`${f}\``)
    ].join('\n');
    writeFileSync(findingFile, findingContent, 'utf8');
    console.log('  ✓ OpenBrain finding saved');
  }

  // 5. Push to GitHub
  console.log('');
  console.log('  📤 Syncing to GitHub...');
  gitCommitAndPush(`context: save session ${timestamp}`);

  // 6. Summary
  console.log('');
  console.log('╔═══════════════════════════════════════════════╗');
  console.log('║   ✓ Context Saved Successfully               ║');
  console.log('╚═══════════════════════════════════════════════╝');
  console.log('');
  console.log('  Next chat can now load this context with:');
  console.log('  $ git pull');
  console.log('  $ node automation/load-context.js');
  console.log('');
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});